### ISSUE TITLE
Change the Signature genes.

### ISSUE THREAD

**Issue by Disha770** [IARCbioinfo/quantiseq-nf#1]
Hi,
I was wondering if I can provide a custom signature gene file in quantiseq?
If yes then can you tell me how can I do that ?
Thank you in advance.

**Comment by nalcala** [comment]
Hi @Disha770 ,
That is a good question. It is definitely possible, but since the whole quantiseq software is neatly packaged inside the docker container icbi/quantiseq2, you would need to manipulate a bit the docker image to change the reference inside it, then generate a new container, and modify the first process of this nextflow pipeline to pull this alternative docker container instead of that at icbi/quantiseq2. 
I can see why you would want to do that, but on our side, we prefer to stick with the original quantiseq signature because it is the one that was published and benchmarked by the authors, so changing it would require a lot of care and testing that we cannot do at the moment.
A good alternative for you might be to use the R package immunedeconv https://github.com/icbi-lab/immunedeconv, which allows to switch between several signature matrices including that from quantiseq, CIBERSORT, and such. I think you could even use your own with the function *deconvolute_quantiseq.default(my_matrix)*. Be careful though that you need to do the sample preprocessing yourself then, to be sure that you the signature and your data have been generated in a similar way as they nicely do with quanTIseq.

I am closing the issue because I think this is a general question about software quanTIseq and not this pipeline, which merely allows to launch quantiseq with nextflow but does not intend to change the program itself.

I hope I was of some help. All the best for your study!

Nicolas
